---
- name: Install common dependencies
  package:
    name:
      - wget

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install APM Server
  package:
    name: "apm-server"
    state: present

- name: Deploy service configuration
  template:
    src: apm-server.yml.j2
    dest: /etc/apm-server/apm-server.yml
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apm-server

- name: Ensure the APM service is enabled and started
  service:
    name: apm-server
    state: started
    enabled: yes
