---
- name: Install prerequisites
  apt:
    name: "{{ apm_server_prereq }}"
    state: present

- name: Add the Elastic APT repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add the Elastic APT repository
  apt_repository:
    repo: "{{ apm_server_elastic_repo_url }}"
    state: present